### Add Todo
POST http://localhost:3000/todos
Content-Type: application/json

{
  "task": "gym"
}

###

### Get All Todos
GET http://localhost:3000/todos

###

### Get Todo by ID
GET http://localhost:3000/todos/1

###

### Delete Todo by ID
DELETE http://localhost:3000/todos/1

###

### Mark Todo as Done
PATCH http://localhost:3000/todos/1

###

### Update Todo
PUT http://localhost:3000/todos/3
Content-Type: application/json

{
  "task": "study"
}